apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
#  storageClassName: manual  no need to specify because we put it in defalut storage class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
